CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR VARCHAR(10),
	NUM_PAG INT(10),
	NOME_EDIT VARCHAR(30),
	VALOR_LIVRO FLOAT(10),
	UF_EDIT VARCHAR(2),
	ANO_PUBL VARCHAR(4)
);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAG, NOME_EDIT, VALOR_LIVRO, UF_EDIT, ANO_PUBL) VALUES('Cavaleiro Real', 'Ana Claudia', 'FEMININO', 465, 'ATLAS', 49.9, 'RJ', '2009'),
('SQL para leigos', 'João Nunes', 'MASCULINO', 450, 'Addison', 98, 'SP', '2018'), 
('Receitas Caseiras', 'Celia Tavares', 'FEMININO', 210, 'ATLAS', 45, 'RJ', '2008'),
('Pessoas Efetivas', 'Eduardo Santos', 'MASCULINO', 390, 'BETA', 78.99, 'RJ', '2018'),
('Habitos Saudáveis', 'Eduardo Santos', 'MASCULINO', 630, 'BETA', 150.98, 'RJ', '2019'),
('A Casa Marrom', 'Hermes Macedo', 'MASCULINO', 250, 'BUBBA', 60, 'MG', '2016'),
('Estacio Querido', 'Geraldo Francisco', 'MASCULINO', 310, 'INSIGNIA', 100, 'ES', '2015'),
('Pra sempre amigas', 'Leda Silva', 'FEMININO', 510, 'INSIGNIA', 78.98, 'ES', '2011'),
('Copas Inesqueciveis', 'Marco Alcantara', 'MASCULINO', 200, 'LARSON', 130.98, 'RS', '2018'),
('O poder da mente', 'Clara Mafra', 'FEMININO', 120, 'CONTINENTAL', 56.58, 'SP', '2017');

SELECT * FROM LIVROS;

SELECT NOME_LIVRO, NOME_EDIT FROM LIVROS;

SELECT NOME_LIVRO, UF_EDIT FROM LIVROS WHERE SEXO_AUTOR = 'MASCULINO';

SELECT NOME_LIVRO, NUM_PAG FROM LIVROS WHERE SEXO_AUTOR = 'FEMININO';

SELECT VALOR_LIVRO FROM LIVROS WHERE UF_EDIT ='SP';

SELECT NOME_AUTOR, SEXO_AUTOR, UF_EDIT FROM LIVROS WHERE UF_EDIT ='RJ' OR UF_EDIT='SP';

